[package]
name = "a_star"
version = "0.1.0"
authors = ["Vikrom Narula <djnarula@gmail.com>"]
edition = "2018"

[[bench]]
name = "bench"
harness = false

[dependencies]
num-traits = "0.2.14"
indexmap = "1.6.0"
rayon = "1.5.0"
itertools = "0.9.0"
criterion = "0.3.3"
pathfinding = "2.0.4"
